services:
    FIP.registration.form.type:
            class: FIPBank\UserBundle\Form\Type\RegistrationFormType
            arguments: [%fos_user.model.user.class%]
            tags:
                - { name: form.type, alias: FIP_REG_FORM }
