## YAML Template.

FIPBank\UserBundle\Entity\User:
    type:  entity
    table: user_accounts
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
                
    fields:
        accountNumber:
            type: integer
            length: 100