fip_privacyStatement:
    path: /privacyStatement
    defaults: {_controller: FIPBankBundle:Default:privacyStatement }
    
fip_termsConditions:
    path: /terms
    defaults: {_controller: FIPBankBundle:Default:termsCondition }

fip_managementBoard:
    path: /bom
    defaults: {_controller: FIPBankBundle:Default:managementBoard }

fip_valuesBeliefs:
    path: /vb
    defaults: {_controller: FIPBankBundle:Default:valuesAndBeliefs }

fip_branchLocator:
    path: /branchLocator
    defaults: {_controller: FIPBankBundle:Default:branchLocator }
    
fip_RoleSelector:
    path: /ps
    defaults: {_controller: FIPBankBundle:Default:roleSelector }
#------------------------------------------------------------#


#------------------------------------------------------------#

User:
    path: fb/user
    defaults: {_controller: FIPBankBundle:Customer:index }
    
superAdmin:
    path: /superAdmin/
    defaults: {_controller: FIPBankBundle:SuperAdmin:index }
    
Admin:    
    path: /admin/
    defaults: {_controller: FIPBankBundle:Admin:index }
    
#------------------------------------------------------------#
CreateAdmin:    
    path: /superAdmin/CreateAdmin
    defaults: {_controller: FIPBankBundle:SuperAdmin:createAdmin }
CreateAdminConfirm:    
    path: /admin/CreateAdmin
    defaults: {_controller: FIPBankBundle:SuperAdmin:createAdminConfirm }
    
ViewHistory:    
    path: fb/history/{userId}
    defaults: {_controller: FIPBankBundle:Customer:viewHistory }

passwordChangedSuccessfully:    
    path: fb/passwordChanged/
    defaults: {_controller: FIPBankBundle:CommonAction:profileSettingsSuccess }
    
#------------------------------------------------------------#




    
#-------------------------Profile Settings-----------------------------------#
    
customerSettings:
    path: /customer/Settings
    defaults: {_controller: FIPBankBundle:Customer:settings }
    

profileSettings:
    path: /profile/Settings
    defaults: {_controller: FIPBankBundle:CommonAction:profileSettings }
    
#------------------------------------------------------------#
