fip_homepage:
    path:     /
    defaults: { _controller: FIPBundle:Default:index }
    
fip_privacyStatement:
    path: /privacyStatement
    defaults: {_controller: FIPBundle:Default:privacyStatement }
    
fip_termsConditions:
    path: /terms
    defaults: {_controller: FIPBundle:Default:termsCondition }

fip_managementBoard:
    path: /bom
    defaults: {_controller: FIPBundle:Default:managementBoard }

fip_valuesBeliefs:
    path: /vb
    defaults: {_controller: FIPBundle:Default:valuesAndBeliefs }

fip_branchLocator:
    path: /branchLocator
    defaults: {_controller: FIPBundle:Default:branchLocator }

